### ISSUE TITLE
Doesn't work in Chrome

### ISSUE THREAD

**Issue by AEtherSurfer** [AEtherSurfer/Anaddire#1]

**Comment by AEtherSurfer** [comment]
Anyone want to check if it works in Opera?  Does Safari have userscript support?

**Comment by bobthecow** [comment]
greasemonkey support for all webkit browsers: http://8-p.info/greasekit/

**Comment by AEtherSurfer** [comment]
I get the same NO_MODIFICATION_ALLOWED_ERR in greasekit as I do in chrome.
webkit doesn't like the way I try to swap out the head node with innerHTML =
